title: ism.raw
description: 35mm film photography. Portraits, lines, and geometrical patterns.
url: "https://ism-raw-portfolio.pages.dev"
baseurl: ""

# Build settings
markdown: kramdown
permalink: pretty

# Exclude from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
